-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

DROP TABLE IF EXISTS itinerary_landmark;
DROP TABLE IF EXISTS itinerary;
DROP TABLE IF EXISTS landmark;
DROP TABLE IF EXISTS users;


CREATE TABLE IF NOT EXISTS public.users
(
    user_id SERIAL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(200) COLLATE pg_catalog."default" NOT NULL,
    role character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT users_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.itinerary
(
    id serial NOT NULL,
    user_id integer NOT NULL,
    date date NOT NULL,
    start_location character varying(300) NOT NULL,
    end_location character varying(300) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.landmark
(
    id serial NOT NULL,
    place_id character varying(500) NOT NULL,
    type character varying(300) NOT NULL DEFAULT 'other',
    city character varying(300) NOT NULL DEFAULT 'other',
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.itinerary_landmark
(
    itinerary_id integer NOT NULL,
    landmark_id integer NOT NULL,
    CONSTRAINT pk_itinerary_landmark PRIMARY KEY (itinerary_id, landmark_id)
);

ALTER TABLE IF EXISTS public.itinerary
    ADD CONSTRAINT fk_itinerary_userid FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.itinerary_landmark
    ADD CONSTRAINT fk_itinerary_landmark_itineraryid FOREIGN KEY (itinerary_id)
    REFERENCES public.itinerary (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.itinerary_landmark
    ADD CONSTRAINT fk_itinerary_landmark_landmarkid FOREIGN KEY (landmark_id)
    REFERENCES public.landmark (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;